modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
issueTrackerURL="https://github.com/lazyMods/ExNihiloAutomation/issues"
[[mods]]
modId="exnihiloauto"
version="${file.jarVersion}"
displayName="Ex Nihilo: Automation"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/exnihilo-automation"
logoFile="examplemod.png"
credits="Me"
authors="lazy"
description='''
Automation for Ex Nihilo Sequentia
'''
[[dependencies.exnihiloauto]]
modId="exnihilosequentia"
mandatory=true
versionRange="[1.16-2.0.2.8,]"
ordering="NONE"
side="BOTH"